
import MpvActionCreator from '../actions/MpvActionCreator';
import PlayerActionCreator from '../actions/PlayerActionCreator';


namespace mpv {

    // Main id; assoiciated with one mpv instance. Generated by mpv-http-router
    export type Id = string;

    // this is (intended to be) a complete list (mpv@0.28.2)
    export enum Event {
        audioReconfig = 'audio-reconfig',
        endFile = 'end-file',
        fileLoaded = 'file-loaded',
        idle = 'idle',
        logMessage = 'log-message',
        pause = 'pause',
        playbackRestart = 'playback-restart',
        propertyChange = 'property-change',
        seek = 'seek',
        shutdown = 'shutdown',
        startFile = 'start-file',
        unpause = 'unpause',
        videoReconfig = 'video-reconfig',
    }

    export namespace Command {

        export enum Input {
            cycle = 'cycle',
            playlistPrev = 'playlist-prev',
            playlistNext = 'playlist-next',
            seek = 'seek',
            stop = 'stop',
        }

        export enum SeekType {
            relative = 'relative',
            absolute = 'absolute',
            absolutePercent = 'absolute-percent',
            relativePercent = 'relative-percent',
            exact = 'exact',
            keyframes = 'keyframes',
        }

        // this is (intended to be) a complete list (mpv@0.28.2)
        export enum IPC {
            clientName = "client_name",
            getTimeUs = "get_time_us",
            getProperty = "get_property",
            getPropertyString = "get_property_string",
            setProperty = "set_property",
            setPropertyString = "set_property_string",
            observeProperty = "observe_property",
            observePropertyString = "observe_property_string",
            unobserveProperty = "unobserve_property",
            requestLogMessages = "request_log_messages",
            enableEvent = "enable_event",
            disableEvent = "disable_event",
            getVersion = "get_version",
        }
    }


    export enum TrackDataProp {
        id = "id",
        type = "type",
        srcId = "src-id",
        title = "title",
        lang = "lang",
        albumart = "albumart",
        default = "default",
        forced = "forced",
        external = "external",
        selected = "selected",
        ffIndex = "ff-index",
        decoderDesc = "decoder-desc",
        codec = "codec",
        demuxW = "demux-w",
        demuxH = "demux-h",
        demuxFps = "demux-fps",
        demuxChannelCount = "demux-channel-count",
        demuxChannels = "demux-channels",
        demuxSamplerate = "demux-samplerate",
        audioChannels = "audio-channels",
    }

    export enum TrackDataType {
        audio = "audio",
        video = "video",
        sub = "sub",
    }

    export class TrackData {
        constructor(properties) {
            for (let [key, val] of Object.entries(properties))
                this.setProperty(key, val);
        }

        setProperty(name: string, value: any): void {
            this[trackPropertyReverseMap[name]] = value;
        }

        get caption(): string {
            return this.title || this.decoderDesc;
        }

        id: number;
        type: TrackDataType;
        srcId: number;
        title: string;
        lang: string;
        albumart: boolean;
        default: boolean;
        forced: boolean;
        external: boolean;
        selected: boolean;
        ffIndex: number;
        audioChannels?: number;
        decoderDesc?: string;
        codec: string;
        demuxW?: number;
        demuxH?: number;
        demuxFps?: number;
        demuxChannelCount?: number;
        demuxChannels?: string;
        demuxSamplerate?: number;
    }

    export interface PlaylistItem {
        filename: string;
        title?: string;
        current?: boolean,
        playing?: boolean,
    }

    class Remote {
        private _id: Id;

        constructor(id: Id) {
            this._id = id;
        }

        cyclePause(): void {
            MpvActionCreator.cyclePause(this._id);
        }

        cycleMute(): void {
            MpvActionCreator.cycleMute(this._id);
        }

        setVolume(value: number): void {
            MpvActionCreator.setVolume(this._id, value);
        }

        playlistPrev(): void {
            MpvActionCreator.playlistPrev(this._id);
        }

        playlistNext(): void {
            MpvActionCreator.playlistNext(this._id);
        }

        seek(seconds: number, type: Command.SeekType = Command.SeekType.relative): void {
            MpvActionCreator.seek(this._id, seconds, type);
        }

        setAudioTrack(aid: number) {
            MpvActionCreator.setAudioTrack(this._id, aid)
        }

        setSubtitleTrack(sid: number) {
            MpvActionCreator.setSubtitleTrack(this._id, sid)
        }

        cycleAudioTracks() {
            MpvActionCreator.cycleAudioTracks(this._id);
        }

        cycleSubtitleTracks() {
            MpvActionCreator.cycleSubtitleTracks(this._id);
        }

        cycleFullscreen() {
            MpvActionCreator.cycleFullscreen(this._id);
        }

        setPlaylistPosition(idx: number) {
            MpvActionCreator.setPlaylistPosition(this._id, idx);
        }

        stop() {
            MpvActionCreator.stop(this._id);
        }
    }

    export type TrackDataMap = {[s: number]: TrackData};

    export interface TrackListDataMap {
        video: TrackDataMap;
        audio: TrackDataMap;
        sub: TrackDataMap;
    }

    export class Player {

        constructor(id: Id, properties: object, enabled: boolean = true) {
            this.id = id;
            this.enabled = enabled;

            this.remote = new Remote(id);

            for (let [key, val] of Object.entries(properties))
                this.setProperty(key, val);
        }

        setProperty(name: string, value: any): void {
            if (name == mpv.Property.trackList) {
                let res = [];
                this.trackListMap = {video: {}, audio: {}, sub: {}};
                for (let track of value) {
                    let td = new TrackData(track);
                    this.trackListMap[td.type][td.id] = td;
                    res.push(td);
                }
                value = res;
            }

            this[propertyReverseMap[name]] = value;
        }

        toogleOpen(): void {
            PlayerActionCreator.toogleOpen(this.id);
        }

        open(): void {
            PlayerActionCreator.open(this.id);
        }

        get caption(): string {
            return this.streamPath.startsWith('http') ? this.mediaTitle : this.filename;
        }

        id: Id;
        enabled: boolean;
        opened: boolean = true;
        trackListMap: TrackListDataMap = {video: {}, audio: {}, sub: {}};

        remote: Remote;

        _3dlutSize?: any;
        abLoopA?: any;
        abLoopB?: any;
        accessReferences?: any;
        ad?: any;
        adLavcAc3drc?: any;
        adLavcDownmix?: any;
        adLavcO?: any;
        adLavcThreads?: any;
        adSpdifDtshd?: any;
        af?: any;
        afDefaults?: any;
        afMetadata?: any;
        aid?: number;
        alang?: any;
        alpha?: any;
        angle?: any;
        ao?: any;
        aoMute?: any;
        aoNullBrokenDelay?: any;
        aoNullBrokenEof?: any;
        aoNullBuffer?: any;
        aoNullChannelLayouts?: any;
        aoNullLatency?: any;
        aoNullOutburst?: any;
        aoNullSpeed?: any;
        aoNullUntimed?: any;
        aoPcmAppend?: any;
        aoPcmFile?: any;
        aoPcmWaveheader?: any;
        aoVolume?: any;
        aspect?: any;
        ass?: any;
        assForceMargins?: any;
        assForceStyle?: any;
        assHinting?: any;
        assLineSpacing?: any;
        assStyles?: any;
        assUseMargins?: any;
        assVsfilterAspectCompat?: any;
        assVsfilterBlurCompat?: any;
        assVsfilterColorCompat?: any;
        audio?: any;
        audioBitrate?: any;
        audioBuffer?: any;
        audioChannels?: any;
        audioClientName?: any;
        audioCodec?: any;
        audioCodecName?: any;
        audioDelay?: any;
        audioDemuxer?: any;
        audioDevice?: any;
        audioDeviceList?: any;
        audioDisplay?: any;
        audioExclusive?: any;
        audioFallbackToNull?: any;
        audioFile?: any;
        audiofile?: any;
        audioFileAuto?: any;
        audioFilePaths?: any;
        audioFiles?: any;
        audioFormat?: any;
        audioNormalizeDownmix?: any;
        audioOutParams?: any;
        audioParams?: any;
        audioPitchCorrection?: any;
        audioPts?: any;
        audioSamplerate?: any;
        audioSpdif?: any;
        audioSpeedCorrection?: any;
        audioStreamSilence?: any;
        audioWaitOpen?: any;
        autofit?: any;
        autofitLarger?: any;
        autofitSmaller?: any;
        autoloadFiles?: any;
        autosub?: any;
        autosubMatch?: any;
        autosync?: any;
        avsync?: any;
        background?: any;
        blendSubtitles?: any;
        blurayDevice?: any;
        border?: any;
        brightness?: any;
        cache?: any;
        cacheBackbuffer?: any;
        cacheBufferingState?: any;
        cacheDefault?: any;
        cacheFile?: any;
        cacheFileSize?: any;
        cacheFree?: any;
        cacheIdle?: any;
        cacheInitial?: any;
        cachePause?: any;
        cachePercent?: any;
        cacheSecs?: any;
        cacheSeekMin?: any;
        cacheSize?: any;
        cacheSpeed?: any;
        cacheUsed?: any;
        chapter?: any;
        chapterList?: any;
        chapterMergeThreshold?: any;
        chapterMetadata?: any;
        chapters?: any;
        chapterSeekThreshold?: any;
        chaptersFile?: any;
        clock?: any;
        cocoaForceDedicatedGpu?: any;
        colormatrix?: any;
        colormatrixGamma?: any;
        colormatrixInputRange?: any;
        colormatrixPrimaries?: any;
        config?: any;
        configDir?: any;
        containerFps?: any;
        contrast?: any;
        cookies?: any;
        cookiesFile?: any;
        coreaudioChangePhysicalFormat?: any;
        coreaudioSpdifHack?: any;
        coreIdle?: any;
        correctDownscaling?: any;
        correctPts?: any;
        cscale?: any;
        cscaleAntiring?: any;
        cscaleBlur?: any;
        cscaleClamp?: any;
        cscaleCutoff?: any;
        cscaleParam1?: any;
        cscaleParam2?: any;
        cscaleRadius?: any;
        cscaleTaper?: any;
        cscaleWblur?: any;
        cscaleWindow?: any;
        cscaleWparam?: any;
        cscaleWtaper?: any;
        cudaDecodeDevice?: any;
        currentAo?: any;
        currentDemuxer?: any;
        currentVo?: any;
        cursorAutohide?: any;
        cursorAutohideDelay?: any;
        cursorAutohideFsOnly?: any;
        deband?: any;
        debandGrain?: any;
        debandIterations?: any;
        debandRange?: any;
        debandThreshold?: any;
        decoderFrameDropCount?: any;
        decoderList?: any;
        deinterlace?: any;
        delay?: any;
        demuxer?: any;
        demuxerCacheDuration?: any;
        demuxerCacheIdle?: any;
        demuxerCacheState?: any;
        demuxerCacheTime?: any;
        demuxerLavfAllowMimetype?: any;
        demuxerLavfAnalyzeduration?: any;
        demuxerLavfBuffersize?: any;
        demuxerLavfFormat?: any;
        demuxerLavfGenptsMode?: any;
        demuxerLavfHacks?: any;
        demuxerLavfO?: any;
        demuxerLavfProbeInfo?: any;
        demuxerLavfProbescore?: any;
        demuxerLavfProbesize?: any;
        demuxerMaxBackBytes?: any;
        demuxerMaxBytes?: any;
        demuxerMkvProbeStartTime?: any;
        demuxerMkvProbeVideoDuration?: any;
        demuxerMkvSubtitlePreroll?: any;
        demuxerMkvSubtitlePrerollSecs?: any;
        demuxerMkvSubtitlePrerollSecsIndex?: any;
        demuxerRawaudioChannels?: any;
        demuxerRawaudioFormat?: any;
        demuxerRawaudioRate?: any;
        demuxerRawvideoCodec?: any;
        demuxerRawvideoFormat?: any;
        demuxerRawvideoFps?: any;
        demuxerRawvideoH?: any;
        demuxerRawvideoMpFormat?: any;
        demuxerRawvideoSize?: any;
        demuxerRawvideoW?: any;
        demuxerReadaheadSecs?: any;
        demuxerSeekableCache?: any;
        demuxerStartTime?: any;
        demuxerThread?: any;
        demuxerViaNetwork?: any;
        dheight?: any;
        discTitle?: any;
        discTitleList?: any;
        discTitles?: any;
        displayFps?: any;
        displayNames?: any;
        displaySyncActive?: any;
        displayTags?: any;
        dither?: any;
        ditherDepth?: any;
        ditherSizeFruit?: any;
        dropFrameCount?: any;
        dscale?: any;
        dscaleAntiring?: any;
        dscaleBlur?: any;
        dscaleClamp?: any;
        dscaleCutoff?: any;
        dscaleParam1?: any;
        dscaleParam2?: any;
        dscaleRadius?: any;
        dscaleTaper?: any;
        dscaleWblur?: any;
        dscaleWindow?: any;
        dscaleWparam?: any;
        dscaleWtaper?: any;
        dtshd?: any;
        dumpStats?: any;
        duration?: number;
        dvbChannel?: any;
        dvbChannelName?: any;
        dvdAngle?: any;
        dvdangle?: any;
        dvdDevice?: any;
        dvdSpeed?: any;
        dwidth?: any;
        edition?: any;
        editionList?: any;
        editions?: any;
        embeddedfonts?: any;
        encoderList?: any;
        end?: any;
        endpos?: any;
        eofReached?: any;
        estimatedDisplayFps?: any;
        estimatedFrameCount?: any;
        estimatedFrameNumber?: any;
        estimatedVfFps?: any;
        externalFile?: any;
        externalFiles?: any;
        fboFormat?: any;
        ffAid?: any;
        ffmpegVersion?: any;
        ffSid?: any;
        ffVid?: any;
        fileFormat?: any;
        fileLocalOptions?: any;
        filename?: string;
        fileSize?: any;
        filteredMetadata?: any;
        fitBorder?: any;
        font?: any;
        forcedsubsonly?: any;
        forceidx?: any;
        forceMediaTitle?: any;
        forceRgbaOsdRendering?: any;
        forceSeekable?: any;
        forceWindow?: any;
        forceWindowPosition?: any;
        format?: any;
        fps?: any;
        framedrop?: any;
        frameDropCount?: any;
        frames?: any;
        fs?: any;
        fsScreen?: any;
        fullscreen?: any;
        gamma?: any;
        gammaAuto?: any;
        gammaFactor?: any;
        gamutWarning?: any;
        gaplessAudio?: any;
        geometry?: any;
        glslShader?: any;
        glslShaders?: any;
        gpuApi?: any;
        gpuContext?: any;
        gpuDebug?: any;
        gpuDumbMode?: any;
        gpuHwdecInterop?: any;
        gpuShaderCacheDir?: any;
        gpuSw?: any;
        gpuTexPadX?: any;
        gpuTexPadY?: any;
        hdrComputePeak?: any;
        hdrToneMapping?: any;
        height?: any;
        hidpiWindowScale?: any;
        hlsBitrate?: any;
        hrSeek?: any;
        hrSeekDemuxerOffset?: any;
        hrSeekFramedrop?: any;
        httpHeaderFields?: any;
        hue?: any;
        hwdec?: any;
        hwdecCodecs?: any;
        hwdecCurrent?: any;
        hwdecImageFormat?: any;
        hwdecInterop?: any;
        hwdecPreload?: any;
        icc3dlutSize?: any;
        iccCacheDir?: any;
        iccContrast?: any;
        iccIntent?: any;
        iccProfile?: any;
        iccProfileAuto?: any;
        idle?: any;
        idleActive?: any;
        idx?: any;
        ignorePathInWatchLaterConfig?: any;
        imageDisplayDuration?: any;
        imageSubsVideoResolution?: any;
        include?: any;
        index?: any;
        initialAudioSync?: any;
        inputAppleremote?: any;
        inputArDelay?: any;
        inputArRate?: any;
        inputConf?: any;
        inputCursor?: any;
        inputDefaultBindings?: any;
        inputDoubleclickTime?: any;
        inputFile?: any;
        inputIpcServer?: any;
        inputKeyFifoSize?: any;
        inputMediaKeys?: any;
        inputRightAltGr?: any;
        inputTerminal?: any;
        inputTest?: any;
        inputUnixSocket?: any;
        inputVoKeyboard?: any;
        inputX11Keyboard?: any;
        interpolation?: any;
        interpolationThreshold?: any;
        keepaspect?: any;
        keepaspectWindow?: any;
        keepOpen?: any;
        keepOpenPause?: any;
        lavfiComplex?: any;
        length?: any;
        linearScaling?: any;
        loadScripts?: any;
        loadStatsOverlay?: any;
        loadUnsafePlaylists?: any;
        logFile?: any;
        loop?: any;
        loopFile?: any;
        loopPlaylist?: any;
        lua?: any;
        luaOpts?: any;
        mc?: any;
        mediaKeys?: any;
        mediaTitle?: string;
        mergeFiles?: any;
        metadata?: any;
        mfFps?: any;
        mfType?: any;
        mistimedFrameCount?: any;
        mixerActive?: any;
        mkvSubtitlePreroll?: any;
        monitoraspect?: any;
        monitorpixelaspect?: any;
        mouseMovements?: any;
        mpvConfiguration?: any;
        mpvVersion?: any;
        msgColor?: any;
        msgcolor?: any;
        msgLevel?: any;
        msgModule?: any;
        msgmodule?: any;
        msgTime?: any;
        mute?: any;
        name?: any;
        nativeFs?: any;
        nativeKeyrepeat?: any;
        networkTimeout?: any;
        noar?: any;
        noautosub?: any;
        noconsolecontrols?: any;
        nosound?: any;
        o?: any;
        oac?: any;
        oacopts?: any;
        oafirst?: any;
        oaoffset?: any;
        oautofps?: any;
        ocopyts?: any;
        of?: any;
        ofopts?: any;
        ofps?: any;
        oharddup?: any;
        omaxfps?: any;
        ometadata?: any;
        onAllWorkspaces?: any;
        oneverdrop?: any;
        ontop?: any;
        ontopLevel?: any;
        openglBackend?: any;
        openglCheckPattern?: any;
        openglDebug?: any;
        openglDumbMode?: any;
        openglEarlyFlush?: any;
        openglEs?: any;
        openglFboFormat?: any;
        openglGamma?: any;
        openglGlfinish?: any;
        openglHwdecInterop?: any;
        openglPbo?: any;
        openglRectangleTextures?: any;
        openglRestrict?: any;
        openglShader?: any;
        openglShaderCacheDir?: any;
        openglShaders?: any;
        openglSw?: any;
        openglSwapinterval?: any;
        openglTexPadX?: any;
        openglTexPadY?: any;
        openglVsyncFences?: any;
        openglWaitvsync?: any;
        optionInfo?: any;
        options?: any;
        orawts?: any;
        orderedChapters?: any;
        orderedChaptersFiles?: any;
        osc?: any;
        osdAlignX?: any;
        osdAlignY?: any;
        osdAssCc?: any;
        osdBackColor?: any;
        osdBar?: any;
        osdBarAlignX?: any;
        osdBarAlignY?: any;
        osdBarH?: any;
        osdBarW?: any;
        osdBlur?: any;
        osdBold?: any;
        osdBorderColor?: any;
        osdBorderSize?: any;
        osdColor?: any;
        osdDuration?: any;
        osdFont?: any;
        osdFontSize?: any;
        osdFractions?: any;
        osdHeight?: any;
        osdItalic?: any;
        osdJustify?: any;
        osdLevel?: any;
        osdlevel?: any;
        osdMarginX?: any;
        osdMarginY?: any;
        osdMsg1?: any;
        osdMsg2?: any;
        osdMsg3?: any;
        osdPar?: any;
        osdPlayingMsg?: any;
        osdScale?: any;
        osdScaleByWindow?: any;
        osdShadowColor?: any;
        osdShadowOffset?: any;
        osdSpacing?: any;
        osdStatusMsg?: any;
        osdSymCc?: any;
        osdWidth?: any;
        ovc?: any;
        ovcopts?: any;
        ovfirst?: any;
        ovoffset?: any;
        packetAudioBitrate?: any;
        packetSubBitrate?: any;
        packetVideoBitrate?: any;
        panscan?: any;
        partiallySeekable?: any;
        path?: string;
        pause?: boolean;
        pausedForCache?: any;
        percentPos?: any;
        playbackAbort?: any;
        playbackTime?: any;
        playingMsg?: any;
        playlist?: PlaylistItem[];
        playlistCount?: number;
        playlistPos?: number;
        playlistPos1?: number;
        playlistStart?: any;
        playtimeRemaining?: any;
        prefetchPlaylist?: any;
        profile?: any;
        profileList?: any;
        program?: any;
        propertyList?: any;
        protocolList?: any;
        quiet?: any;
        reallyQuiet?: any;
        rebaseStartTime?: any;
        recordFile?: any;
        referrer?: any;
        replaygain?: any;
        replaygainClip?: any;
        replaygainFallback?: any;
        replaygainPreamp?: any;
        resetOnNextFile?: any;
        resumePlayback?: any;
        rightAltGr?: any;
        rtspTransport?: any;
        saturation?: any;
        savePositionOnQuit?: any;
        scale?: any;
        scaleAntiring?: any;
        scaleBlur?: any;
        scaleClamp?: any;
        scaleCutoff?: any;
        scaleParam1?: any;
        scaleParam2?: any;
        scaleRadius?: any;
        scalerLutSize?: any;
        scalerResizesOnly?: any;
        scaleTaper?: any;
        scaleWblur?: any;
        scaleWindow?: any;
        scaleWparam?: any;
        scaleWtaper?: any;
        screen?: any;
        screenshotDirectory?: any;
        screenshotFormat?: any;
        screenshotHighBitDepth?: any;
        screenshotJpegQuality?: any;
        screenshotJpegSourceChroma?: any;
        screenshotPngCompression?: any;
        screenshotPngFilter?: any;
        screenshotTagColorspace?: any;
        screenshotTemplate?: any;
        script?: any;
        scriptOpts?: any;
        scripts?: any;
        secondarySid?: any;
        seekable?: any;
        seeking?: any;
        sharpen?: any;
        shuffle?: any;
        sid?: number;
        sigmoidCenter?: any;
        sigmoidSlope?: any;
        sigmoidUpscaling?: any;
        slang?: any;
        snapWindow?: any;
        softvol?: any;
        softvolMax?: any;
        speed?: any;
        spirvCompiler?: any;
        spugauss?: any;
        srate?: any;
        ss?: any;
        sstep?: any;
        start?: any;
        statusMsg?: any;
        stopPlaybackOnInitFailure?: any;
        stopScreensaver?: any;
        stopXscreensaver?: any;
        streamDump?: any;
        streamEnd?: any;
        streamLavfO?: any;
        streamOpenFilename?: any;
        streamPath?: string;
        streamPos?: any;
        stretchDvdSubs?: any;
        stretchImageSubsToScreen?: any;
        sub?: any;
        subAlignX?: any;
        subAlignY?: any;
        subAss?: any;
        subAssForceMargins?: any;
        subAssForceStyle?: any;
        subAssHinting?: any;
        subAssJustify?: any;
        subAssLineSpacing?: any;
        subAssOverride?: any;
        subAssScaleWithWindow?: any;
        subAssShaper?: any;
        subAssStyles?: any;
        subAssVsfilterAspectCompat?: any;
        subAssVsfilterBlurCompat?: any;
        subAssVsfilterColorCompat?: any;
        subAuto?: any;
        subBackColor?: any;
        subBitrate?: any;
        subBlur?: any;
        subBold?: any;
        subBorderColor?: any;
        subBorderSize?: any;
        subClearOnSeek?: any;
        subCodepage?: any;
        subColor?: any;
        subcp?: any;
        subCreateCcTrack?: any;
        subDelay?: any;
        subdelay?: any;
        subDemuxer?: any;
        subFile?: any;
        subfile?: any;
        subFilePaths?: any;
        subFiles?: any;
        subFilterSdh?: any;
        subFilterSdhHarder?: any;
        subFixTiming?: any;
        subFont?: any;
        subfont?: any;
        subFontSize?: any;
        subfontTextScale?: any;
        subForcedOnly?: any;
        subFps?: any;
        subfps?: any;
        subFuzziness?: any;
        subGauss?: any;
        subGray?: any;
        subItalic?: any;
        subJustify?: any;
        subMarginX?: any;
        subMarginY?: any;
        subPos?: any;
        subpos?: any;
        subScale?: any;
        subScaleByWindow?: any;
        subScaleWithWindow?: any;
        subShadowColor?: any;
        subShadowOffset?: any;
        subSpacing?: any;
        subSpeed?: any;
        subText?: any;
        subTextAlignX?: any;
        subTextAlignY?: any;
        subTextBackColor?: any;
        subTextBlur?: any;
        subTextBold?: any;
        subTextBorderColor?: any;
        subTextBorderSize?: any;
        subTextColor?: any;
        subTextFont?: any;
        subTextFontSize?: any;
        subTextItalic?: any;
        subTextMarginX?: any;
        subTextMarginY?: any;
        subTextShadowColor?: any;
        subTextShadowOffset?: any;
        subTextSpacing?: any;
        subUseMargins?: any;
        subVisibility?: any;
        swapchainDepth?: any;
        swsCgb?: any;
        swsChs?: any;
        swsCs?: any;
        swsCvs?: any;
        swsLgb?: any;
        swsLs?: any;
        swsScaler?: any;
        targetPrim?: any;
        targetTrc?: any;
        taskbarProgress?: any;
        teletextPage?: any;
        temporalDither?: any;
        temporalDitherPeriod?: any;
        terminal?: any;
        termOsd?: any;
        termOsdBar?: any;
        termOsdBarChars?: any;
        termPlayingMsg?: any;
        termStatusMsg?: any;
        timePos?: number;
        timeRemaining?: any;
        timeStart?: any;
        title?: any;
        tlsCaFile?: any;
        tlsCertFile?: any;
        tlsKeyFile?: any;
        tlsVerify?: any;
        toneMapping?: any;
        toneMappingDesaturate?: any;
        toneMappingParam?: any;
        totalAvsyncChange?: any;
        trackAutoSelection?: any;
        trackList?: TrackData[];
        tscale?: any;
        tscaleAntiring?: any;
        tscaleBlur?: any;
        tscaleClamp?: any;
        tscaleCutoff?: any;
        tscaleParam1?: any;
        tscaleParam2?: any;
        tscaleRadius?: any;
        tscaleTaper?: any;
        tscaleWblur?: any;
        tscaleWindow?: any;
        tscaleWparam?: any;
        tscaleWtaper?: any;
        tvBrightness?: any;
        tvChannel?: any;
        tvContrast?: any;
        tvFreq?: any;
        tvHue?: any;
        tvNorm?: any;
        tvSaturation?: any;
        tvScan?: any;
        tvscan?: any;
        untimed?: any;
        useEmbeddedIccProfile?: any;
        useFiledirConf?: any;
        userAgent?: any;
        vd?: any;
        vdLavcBitexact?: any;
        vdLavcCheckHwProfile?: any;
        vdLavcDr?: any;
        vdLavcFast?: any;
        vdLavcFramedrop?: any;
        vdLavcO?: any;
        vdLavcShowAll?: any;
        vdLavcSkipframe?: any;
        vdLavcSkipidct?: any;
        vdLavcSkiploopfilter?: any;
        vdLavcSoftwareFallback?: any;
        vdLavcThreads?: any;
        vf?: any;
        vfDefaults?: any;
        vfMetadata?: any;
        vid?: any;
        video?: any;
        videoAlignX?: any;
        videoAlignY?: any;
        videoAspect?: any;
        videoAspectMethod?: any;
        videoBitrate?: any;
        videoCodec?: any;
        videoDecParams?: any;
        videoFormat?: any;
        videoFrameInfo?: any;
        videoOsd?: any;
        videoOutParams?: any;
        videoOutputLevels?: any;
        videoPanX?: any;
        videoPanY?: any;
        videoParams?: any;
        videoRotate?: any;
        videoSpeedCorrection?: any;
        videoStereoMode?: any;
        videoSync?: any;
        videoSyncAdropSize?: any;
        videoSyncMaxAudioChange?: any;
        videoSyncMaxVideoChange?: any;
        videotoolboxFormat?: any;
        videoUnscaled?: any;
        videoZoom?: any;
        vlang?: any;
        vo?: any;
        voConfigured?: any;
        voDelayedFrameCount?: any;
        voDropFrameCount?: any;
        voImageFormat?: any;
        voImageHighBitDepth?: any;
        voImageJpegQuality?: any;
        voImageJpegSourceChroma?: any;
        voImageOutdir?: any;
        voImagePngCompression?: any;
        voImagePngFilter?: any;
        voImageTagColorspace?: any;
        volume?: number;
        volumeMax?: any;
        voNullFps?: any;
        voPasses?: any;
        voTct256?: any;
        voTctAlgo?: any;
        voTctHeight?: any;
        voTctWidth?: any;
        vsyncJitter?: any;
        vsyncRatio?: any;
        watchLaterDirectory?: any;
        wid?: any;
        width?: any;
        windowDragging?: any;
        windowMinimized?: any;
        windowScale?: any;
        workingDirectory?: any;
        writeFilenameInWatchLaterConfig?: any;
        x11Name?: any;
        ytdl?: any;
        ytdlFormat?: any;
        ytdlRawOptions?: any;
        assShaper?: any;
        assStyleOverride?: any;
        assScaleWithWindow?: any;
        subAssStyleOverride?: any;
        subPaths?: any;
    }

    // this is (intended to be) a complete list (mpv@0.28.2)
    export enum Property {
        _3dlutSize = "3dlut-size",
        abLoopA = "ab-loop-a",
        abLoopB = "ab-loop-b",
        accessReferences = "access-references",
        ad = "ad",
        adLavcAc3drc = "ad-lavc-ac3drc",
        adLavcDownmix = "ad-lavc-downmix",
        adLavcO = "ad-lavc-o",
        adLavcThreads = "ad-lavc-threads",
        adSpdifDtshd = "ad-spdif-dtshd",
        af = "af",
        afDefaults = "af-defaults",
        afMetadata = "af-metadata",
        aid = "aid",
        alang = "alang",
        alpha = "alpha",
        angle = "angle",
        ao = "ao",
        aoMute = "ao-mute",
        aoNullBrokenDelay = "ao-null-broken-delay",
        aoNullBrokenEof = "ao-null-broken-eof",
        aoNullBuffer = "ao-null-buffer",
        aoNullChannelLayouts = "ao-null-channel-layouts",
        aoNullLatency = "ao-null-latency",
        aoNullOutburst = "ao-null-outburst",
        aoNullSpeed = "ao-null-speed",
        aoNullUntimed = "ao-null-untimed",
        aoPcmAppend = "ao-pcm-append",
        aoPcmFile = "ao-pcm-file",
        aoPcmWaveheader = "ao-pcm-waveheader",
        aoVolume = "ao-volume",
        aspect = "aspect",
        ass = "ass",
        assForceMargins = "ass-force-margins",
        assForceStyle = "ass-force-style",
        assHinting = "ass-hinting",
        assLineSpacing = "ass-line-spacing",
        assStyles = "ass-styles",
        assUseMargins = "ass-use-margins",
        assVsfilterAspectCompat = "ass-vsfilter-aspect-compat",
        assVsfilterBlurCompat = "ass-vsfilter-blur-compat",
        assVsfilterColorCompat = "ass-vsfilter-color-compat",
        audio = "audio",
        audioBitrate = "audio-bitrate",
        audioBuffer = "audio-buffer",
        audioChannels = "audio-channels",
        audioClientName = "audio-client-name",
        audioCodec = "audio-codec",
        audioCodecName = "audio-codec-name",
        audioDelay = "audio-delay",
        audioDemuxer = "audio-demuxer",
        audioDevice = "audio-device",
        audioDeviceList = "audio-device-list",
        audioDisplay = "audio-display",
        audioExclusive = "audio-exclusive",
        audioFallbackToNull = "audio-fallback-to-null",
        audioFile = "audio-file",
        audiofile = "audiofile",
        audioFileAuto = "audio-file-auto",
        audioFilePaths = "audio-file-paths",
        audioFiles = "audio-files",
        audioFormat = "audio-format",
        audioNormalizeDownmix = "audio-normalize-downmix",
        audioOutParams = "audio-out-params",
        audioParams = "audio-params",
        audioPitchCorrection = "audio-pitch-correction",
        audioPts = "audio-pts",
        audioSamplerate = "audio-samplerate",
        audioSpdif = "audio-spdif",
        audioSpeedCorrection = "audio-speed-correction",
        audioStreamSilence = "audio-stream-silence",
        audioWaitOpen = "audio-wait-open",
        autofit = "autofit",
        autofitLarger = "autofit-larger",
        autofitSmaller = "autofit-smaller",
        autoloadFiles = "autoload-files",
        autosub = "autosub",
        autosubMatch = "autosub-match",
        autosync = "autosync",
        avsync = "avsync",
        background = "background",
        blendSubtitles = "blend-subtitles",
        blurayDevice = "bluray-device",
        border = "border",
        brightness = "brightness",
        cache = "cache",
        cacheBackbuffer = "cache-backbuffer",
        cacheBufferingState = "cache-buffering-state",
        cacheDefault = "cache-default",
        cacheFile = "cache-file",
        cacheFileSize = "cache-file-size",
        cacheFree = "cache-free",
        cacheIdle = "cache-idle",
        cacheInitial = "cache-initial",
        cachePause = "cache-pause",
        cachePercent = "cache-percent",
        cacheSecs = "cache-secs",
        cacheSeekMin = "cache-seek-min",
        cacheSize = "cache-size",
        cacheSpeed = "cache-speed",
        cacheUsed = "cache-used",
        chapter = "chapter",
        chapterList = "chapter-list",
        chapterMergeThreshold = "chapter-merge-threshold",
        chapterMetadata = "chapter-metadata",
        chapters = "chapters",
        chapterSeekThreshold = "chapter-seek-threshold",
        chaptersFile = "chapters-file",
        clock = "clock",
        cocoaForceDedicatedGpu = "cocoa-force-dedicated-gpu",
        colormatrix = "colormatrix",
        colormatrixGamma = "colormatrix-gamma",
        colormatrixInputRange = "colormatrix-input-range",
        colormatrixPrimaries = "colormatrix-primaries",
        config = "config",
        configDir = "config-dir",
        containerFps = "container-fps",
        contrast = "contrast",
        cookies = "cookies",
        cookiesFile = "cookies-file",
        coreaudioChangePhysicalFormat = "coreaudio-change-physical-format",
        coreaudioSpdifHack = "coreaudio-spdif-hack",
        coreIdle = "core-idle",
        correctDownscaling = "correct-downscaling",
        correctPts = "correct-pts",
        cscale = "cscale",
        cscaleAntiring = "cscale-antiring",
        cscaleBlur = "cscale-blur",
        cscaleClamp = "cscale-clamp",
        cscaleCutoff = "cscale-cutoff",
        cscaleParam1 = "cscale-param1",
        cscaleParam2 = "cscale-param2",
        cscaleRadius = "cscale-radius",
        cscaleTaper = "cscale-taper",
        cscaleWblur = "cscale-wblur",
        cscaleWindow = "cscale-window",
        cscaleWparam = "cscale-wparam",
        cscaleWtaper = "cscale-wtaper",
        cudaDecodeDevice = "cuda-decode-device",
        currentAo = "current-ao",
        currentDemuxer = "current-demuxer",
        currentVo = "current-vo",
        cursorAutohide = "cursor-autohide",
        cursorAutohideDelay = "cursor-autohide-delay",
        cursorAutohideFsOnly = "cursor-autohide-fs-only",
        deband = "deband",
        debandGrain = "deband-grain",
        debandIterations = "deband-iterations",
        debandRange = "deband-range",
        debandThreshold = "deband-threshold",
        decoderFrameDropCount = "decoder-frame-drop-count",
        decoderList = "decoder-list",
        deinterlace = "deinterlace",
        delay = "delay",
        demuxer = "demuxer",
        demuxerCacheDuration = "demuxer-cache-duration",
        demuxerCacheIdle = "demuxer-cache-idle",
        demuxerCacheState = "demuxer-cache-state",
        demuxerCacheTime = "demuxer-cache-time",
        demuxerLavfAllowMimetype = "demuxer-lavf-allow-mimetype",
        demuxerLavfAnalyzeduration = "demuxer-lavf-analyzeduration",
        demuxerLavfBuffersize = "demuxer-lavf-buffersize",
        demuxerLavfFormat = "demuxer-lavf-format",
        demuxerLavfGenptsMode = "demuxer-lavf-genpts-mode",
        demuxerLavfHacks = "demuxer-lavf-hacks",
        demuxerLavfO = "demuxer-lavf-o",
        demuxerLavfProbeInfo = "demuxer-lavf-probe-info",
        demuxerLavfProbescore = "demuxer-lavf-probescore",
        demuxerLavfProbesize = "demuxer-lavf-probesize",
        demuxerMaxBackBytes = "demuxer-max-back-bytes",
        demuxerMaxBytes = "demuxer-max-bytes",
        demuxerMkvProbeStartTime = "demuxer-mkv-probe-start-time",
        demuxerMkvProbeVideoDuration = "demuxer-mkv-probe-video-duration",
        demuxerMkvSubtitlePreroll = "demuxer-mkv-subtitle-preroll",
        demuxerMkvSubtitlePrerollSecs = "demuxer-mkv-subtitle-preroll-secs",
        demuxerMkvSubtitlePrerollSecsIndex = "demuxer-mkv-subtitle-preroll-secs-index",
        demuxerRawaudioChannels = "demuxer-rawaudio-channels",
        demuxerRawaudioFormat = "demuxer-rawaudio-format",
        demuxerRawaudioRate = "demuxer-rawaudio-rate",
        demuxerRawvideoCodec = "demuxer-rawvideo-codec",
        demuxerRawvideoFormat = "demuxer-rawvideo-format",
        demuxerRawvideoFps = "demuxer-rawvideo-fps",
        demuxerRawvideoH = "demuxer-rawvideo-h",
        demuxerRawvideoMpFormat = "demuxer-rawvideo-mp-format",
        demuxerRawvideoSize = "demuxer-rawvideo-size",
        demuxerRawvideoW = "demuxer-rawvideo-w",
        demuxerReadaheadSecs = "demuxer-readahead-secs",
        demuxerSeekableCache = "demuxer-seekable-cache",
        demuxerStartTime = "demuxer-start-time",
        demuxerThread = "demuxer-thread",
        demuxerViaNetwork = "demuxer-via-network",
        dheight = "dheight",
        discTitle = "disc-title",
        discTitleList = "disc-title-list",
        discTitles = "disc-titles",
        displayFps = "display-fps",
        displayNames = "display-names",
        displaySyncActive = "display-sync-active",
        displayTags = "display-tags",
        dither = "dither",
        ditherDepth = "dither-depth",
        ditherSizeFruit = "dither-size-fruit",
        dropFrameCount = "drop-frame-count",
        dscale = "dscale",
        dscaleAntiring = "dscale-antiring",
        dscaleBlur = "dscale-blur",
        dscaleClamp = "dscale-clamp",
        dscaleCutoff = "dscale-cutoff",
        dscaleParam1 = "dscale-param1",
        dscaleParam2 = "dscale-param2",
        dscaleRadius = "dscale-radius",
        dscaleTaper = "dscale-taper",
        dscaleWblur = "dscale-wblur",
        dscaleWindow = "dscale-window",
        dscaleWparam = "dscale-wparam",
        dscaleWtaper = "dscale-wtaper",
        dtshd = "dtshd",
        dumpStats = "dump-stats",
        duration = "duration",
        dvbChannel = "dvb-channel",
        dvbChannelName = "dvb-channel-name",
        dvdAngle = "dvd-angle",
        dvdangle = "dvdangle",
        dvdDevice = "dvd-device",
        dvdSpeed = "dvd-speed",
        dwidth = "dwidth",
        edition = "edition",
        editionList = "edition-list",
        editions = "editions",
        embeddedfonts = "embeddedfonts",
        encoderList = "encoder-list",
        end = "end",
        endpos = "endpos",
        eofReached = "eof-reached",
        estimatedDisplayFps = "estimated-display-fps",
        estimatedFrameCount = "estimated-frame-count",
        estimatedFrameNumber = "estimated-frame-number",
        estimatedVfFps = "estimated-vf-fps",
        externalFile = "external-file",
        externalFiles = "external-files",
        fboFormat = "fbo-format",
        ffAid = "ff-aid",
        ffmpegVersion = "ffmpeg-version",
        ffSid = "ff-sid",
        ffVid = "ff-vid",
        fileFormat = "file-format",
        fileLocalOptions = "file-local-options",
        filename = "filename",
        fileSize = "file-size",
        filteredMetadata = "filtered-metadata",
        fitBorder = "fit-border",
        font = "font",
        forcedsubsonly = "forcedsubsonly",
        forceidx = "forceidx",
        forceMediaTitle = "force-media-title",
        forceRgbaOsdRendering = "force-rgba-osd-rendering",
        forceSeekable = "force-seekable",
        forceWindow = "force-window",
        forceWindowPosition = "force-window-position",
        format = "format",
        fps = "fps",
        framedrop = "framedrop",
        frameDropCount = "frame-drop-count",
        frames = "frames",
        fs = "fs",
        fsScreen = "fs-screen",
        fullscreen = "fullscreen",
        gamma = "gamma",
        gammaAuto = "gamma-auto",
        gammaFactor = "gamma-factor",
        gamutWarning = "gamut-warning",
        gaplessAudio = "gapless-audio",
        geometry = "geometry",
        glslShader = "glsl-shader",
        glslShaders = "glsl-shaders",
        gpuApi = "gpu-api",
        gpuContext = "gpu-context",
        gpuDebug = "gpu-debug",
        gpuDumbMode = "gpu-dumb-mode",
        gpuHwdecInterop = "gpu-hwdec-interop",
        gpuShaderCacheDir = "gpu-shader-cache-dir",
        gpuSw = "gpu-sw",
        gpuTexPadX = "gpu-tex-pad-x",
        gpuTexPadY = "gpu-tex-pad-y",
        hdrComputePeak = "hdr-compute-peak",
        hdrToneMapping = "hdr-tone-mapping",
        height = "height",
        hidpiWindowScale = "hidpi-window-scale",
        hlsBitrate = "hls-bitrate",
        hrSeek = "hr-seek",
        hrSeekDemuxerOffset = "hr-seek-demuxer-offset",
        hrSeekFramedrop = "hr-seek-framedrop",
        httpHeaderFields = "http-header-fields",
        hue = "hue",
        hwdec = "hwdec",
        hwdecCodecs = "hwdec-codecs",
        hwdecCurrent = "hwdec-current",
        hwdecImageFormat = "hwdec-image-format",
        hwdecInterop = "hwdec-interop",
        hwdecPreload = "hwdec-preload",
        icc3dlutSize = "icc-3dlut-size",
        iccCacheDir = "icc-cache-dir",
        iccContrast = "icc-contrast",
        iccIntent = "icc-intent",
        iccProfile = "icc-profile",
        iccProfileAuto = "icc-profile-auto",
        idle = "idle",
        idleActive = "idle-active",
        idx = "idx",
        ignorePathInWatchLaterConfig = "ignore-path-in-watch-later-config",
        imageDisplayDuration = "image-display-duration",
        imageSubsVideoResolution = "image-subs-video-resolution",
        include = "include",
        index = "index",
        initialAudioSync = "initial-audio-sync",
        inputAppleremote = "input-appleremote",
        inputArDelay = "input-ar-delay",
        inputArRate = "input-ar-rate",
        inputConf = "input-conf",
        inputCursor = "input-cursor",
        inputDefaultBindings = "input-default-bindings",
        inputDoubleclickTime = "input-doubleclick-time",
        inputFile = "input-file",
        inputIpcServer = "input-ipc-server",
        inputKeyFifoSize = "input-key-fifo-size",
        inputMediaKeys = "input-media-keys",
        inputRightAltGr = "input-right-alt-gr",
        inputTerminal = "input-terminal",
        inputTest = "input-test",
        inputUnixSocket = "input-unix-socket",
        inputVoKeyboard = "input-vo-keyboard",
        inputX11Keyboard = "input-x11-keyboard",
        interpolation = "interpolation",
        interpolationThreshold = "interpolation-threshold",
        keepaspect = "keepaspect",
        keepaspectWindow = "keepaspect-window",
        keepOpen = "keep-open",
        keepOpenPause = "keep-open-pause",
        lavfiComplex = "lavfi-complex",
        length = "length",
        linearScaling = "linear-scaling",
        loadScripts = "load-scripts",
        loadStatsOverlay = "load-stats-overlay",
        loadUnsafePlaylists = "load-unsafe-playlists",
        logFile = "log-file",
        loop = "loop",
        loopFile = "loop-file",
        loopPlaylist = "loop-playlist",
        lua = "lua",
        luaOpts = "lua-opts",
        mc = "mc",
        mediaKeys = "media-keys",
        mediaTitle = "media-title",
        mergeFiles = "merge-files",
        metadata = "metadata",
        mfFps = "mf-fps",
        mfType = "mf-type",
        mistimedFrameCount = "mistimed-frame-count",
        mixerActive = "mixer-active",
        mkvSubtitlePreroll = "mkv-subtitle-preroll",
        monitoraspect = "monitoraspect",
        monitorpixelaspect = "monitorpixelaspect",
        mouseMovements = "mouse-movements",
        mpvConfiguration = "mpv-configuration",
        mpvVersion = "mpv-version",
        msgColor = "msg-color",
        msgcolor = "msgcolor",
        msgLevel = "msg-level",
        msgModule = "msg-module",
        msgmodule = "msgmodule",
        msgTime = "msg-time",
        mute = "mute",
        name = "name",
        nativeFs = "native-fs",
        nativeKeyrepeat = "native-keyrepeat",
        networkTimeout = "network-timeout",
        noar = "noar",
        noautosub = "noautosub",
        noconsolecontrols = "noconsolecontrols",
        nosound = "nosound",
        o = "o",
        oac = "oac",
        oacopts = "oacopts",
        oafirst = "oafirst",
        oaoffset = "oaoffset",
        oautofps = "oautofps",
        ocopyts = "ocopyts",
        of = "of",
        ofopts = "ofopts",
        ofps = "ofps",
        oharddup = "oharddup",
        omaxfps = "omaxfps",
        ometadata = "ometadata",
        onAllWorkspaces = "on-all-workspaces",
        oneverdrop = "oneverdrop",
        ontop = "ontop",
        ontopLevel = "ontop-level",
        openglBackend = "opengl-backend",
        openglCheckPattern = "opengl-check-pattern",
        openglDebug = "opengl-debug",
        openglDumbMode = "opengl-dumb-mode",
        openglEarlyFlush = "opengl-early-flush",
        openglEs = "opengl-es",
        openglFboFormat = "opengl-fbo-format",
        openglGamma = "opengl-gamma",
        openglGlfinish = "opengl-glfinish",
        openglHwdecInterop = "opengl-hwdec-interop",
        openglPbo = "opengl-pbo",
        openglRectangleTextures = "opengl-rectangle-textures",
        openglRestrict = "opengl-restrict",
        openglShader = "opengl-shader",
        openglShaderCacheDir = "opengl-shader-cache-dir",
        openglShaders = "opengl-shaders",
        openglSw = "opengl-sw",
        openglSwapinterval = "opengl-swapinterval",
        openglTexPadX = "opengl-tex-pad-x",
        openglTexPadY = "opengl-tex-pad-y",
        openglVsyncFences = "opengl-vsync-fences",
        openglWaitvsync = "opengl-waitvsync",
        optionInfo = "option-info",
        options = "options",
        orawts = "orawts",
        orderedChapters = "ordered-chapters",
        orderedChaptersFiles = "ordered-chapters-files",
        osc = "osc",
        osdAlignX = "osd-align-x",
        osdAlignY = "osd-align-y",
        osdAssCc = "osd-ass-cc",
        osdBackColor = "osd-back-color",
        osdBar = "osd-bar",
        osdBarAlignX = "osd-bar-align-x",
        osdBarAlignY = "osd-bar-align-y",
        osdBarH = "osd-bar-h",
        osdBarW = "osd-bar-w",
        osdBlur = "osd-blur",
        osdBold = "osd-bold",
        osdBorderColor = "osd-border-color",
        osdBorderSize = "osd-border-size",
        osdColor = "osd-color",
        osdDuration = "osd-duration",
        osdFont = "osd-font",
        osdFontSize = "osd-font-size",
        osdFractions = "osd-fractions",
        osdHeight = "osd-height",
        osdItalic = "osd-italic",
        osdJustify = "osd-justify",
        osdLevel = "osd-level",
        osdlevel = "osdlevel",
        osdMarginX = "osd-margin-x",
        osdMarginY = "osd-margin-y",
        osdMsg1 = "osd-msg1",
        osdMsg2 = "osd-msg2",
        osdMsg3 = "osd-msg3",
        osdPar = "osd-par",
        osdPlayingMsg = "osd-playing-msg",
        osdScale = "osd-scale",
        osdScaleByWindow = "osd-scale-by-window",
        osdShadowColor = "osd-shadow-color",
        osdShadowOffset = "osd-shadow-offset",
        osdSpacing = "osd-spacing",
        osdStatusMsg = "osd-status-msg",
        osdSymCc = "osd-sym-cc",
        osdWidth = "osd-width",
        ovc = "ovc",
        ovcopts = "ovcopts",
        ovfirst = "ovfirst",
        ovoffset = "ovoffset",
        packetAudioBitrate = "packet-audio-bitrate",
        packetSubBitrate = "packet-sub-bitrate",
        packetVideoBitrate = "packet-video-bitrate",
        panscan = "panscan",
        partiallySeekable = "partially-seekable",
        path = "path",
        pause = "pause",
        pausedForCache = "paused-for-cache",
        percentPos = "percent-pos",
        playbackAbort = "playback-abort",
        playbackTime = "playback-time",
        playingMsg = "playing-msg",
        playlist = "playlist",
        playlistCount = "playlist-count",
        playlistPos = "playlist-pos",
        playlistPos1 = "playlist-pos-1",
        playlistStart = "playlist-start",
        playtimeRemaining = "playtime-remaining",
        prefetchPlaylist = "prefetch-playlist",
        profile = "profile",
        profileList = "profile-list",
        program = "program",
        propertyList = "property-list",
        protocolList = "protocol-list",
        quiet = "quiet",
        reallyQuiet = "really-quiet",
        rebaseStartTime = "rebase-start-time",
        recordFile = "record-file",
        referrer = "referrer",
        replaygain = "replaygain",
        replaygainClip = "replaygain-clip",
        replaygainFallback = "replaygain-fallback",
        replaygainPreamp = "replaygain-preamp",
        resetOnNextFile = "reset-on-next-file",
        resumePlayback = "resume-playback",
        rightAltGr = "right-alt-gr",
        rtspTransport = "rtsp-transport",
        saturation = "saturation",
        savePositionOnQuit = "save-position-on-quit",
        scale = "scale",
        scaleAntiring = "scale-antiring",
        scaleBlur = "scale-blur",
        scaleClamp = "scale-clamp",
        scaleCutoff = "scale-cutoff",
        scaleParam1 = "scale-param1",
        scaleParam2 = "scale-param2",
        scaleRadius = "scale-radius",
        scalerLutSize = "scaler-lut-size",
        scalerResizesOnly = "scaler-resizes-only",
        scaleTaper = "scale-taper",
        scaleWblur = "scale-wblur",
        scaleWindow = "scale-window",
        scaleWparam = "scale-wparam",
        scaleWtaper = "scale-wtaper",
        screen = "screen",
        screenshotDirectory = "screenshot-directory",
        screenshotFormat = "screenshot-format",
        screenshotHighBitDepth = "screenshot-high-bit-depth",
        screenshotJpegQuality = "screenshot-jpeg-quality",
        screenshotJpegSourceChroma = "screenshot-jpeg-source-chroma",
        screenshotPngCompression = "screenshot-png-compression",
        screenshotPngFilter = "screenshot-png-filter",
        screenshotTagColorspace = "screenshot-tag-colorspace",
        screenshotTemplate = "screenshot-template",
        script = "script",
        scriptOpts = "script-opts",
        scripts = "scripts",
        secondarySid = "secondary-sid",
        seekable = "seekable",
        seeking = "seeking",
        sharpen = "sharpen",
        shuffle = "shuffle",
        sid = "sid",
        sigmoidCenter = "sigmoid-center",
        sigmoidSlope = "sigmoid-slope",
        sigmoidUpscaling = "sigmoid-upscaling",
        slang = "slang",
        snapWindow = "snap-window",
        softvol = "softvol",
        softvolMax = "softvol-max",
        speed = "speed",
        spirvCompiler = "spirv-compiler",
        spugauss = "spugauss",
        srate = "srate",
        ss = "ss",
        sstep = "sstep",
        start = "start",
        statusMsg = "status-msg",
        stopPlaybackOnInitFailure = "stop-playback-on-init-failure",
        stopScreensaver = "stop-screensaver",
        stopXscreensaver = "stop-xscreensaver",
        streamDump = "stream-dump",
        streamEnd = "stream-end",
        streamLavfO = "stream-lavf-o",
        streamOpenFilename = "stream-open-filename",
        streamPath = "stream-path",
        streamPos = "stream-pos",
        stretchDvdSubs = "stretch-dvd-subs",
        stretchImageSubsToScreen = "stretch-image-subs-to-screen",
        sub = "sub",
        subAlignX = "sub-align-x",
        subAlignY = "sub-align-y",
        subAss = "sub-ass",
        subAssForceMargins = "sub-ass-force-margins",
        subAssForceStyle = "sub-ass-force-style",
        subAssHinting = "sub-ass-hinting",
        subAssJustify = "sub-ass-justify",
        subAssLineSpacing = "sub-ass-line-spacing",
        subAssOverride = "sub-ass-override",
        subAssScaleWithWindow = "sub-ass-scale-with-window",
        subAssShaper = "sub-ass-shaper",
        subAssStyles = "sub-ass-styles",
        subAssVsfilterAspectCompat = "sub-ass-vsfilter-aspect-compat",
        subAssVsfilterBlurCompat = "sub-ass-vsfilter-blur-compat",
        subAssVsfilterColorCompat = "sub-ass-vsfilter-color-compat",
        subAuto = "sub-auto",
        subBackColor = "sub-back-color",
        subBitrate = "sub-bitrate",
        subBlur = "sub-blur",
        subBold = "sub-bold",
        subBorderColor = "sub-border-color",
        subBorderSize = "sub-border-size",
        subClearOnSeek = "sub-clear-on-seek",
        subCodepage = "sub-codepage",
        subColor = "sub-color",
        subcp = "subcp",
        subCreateCcTrack = "sub-create-cc-track",
        subDelay = "sub-delay",
        subdelay = "subdelay",
        subDemuxer = "sub-demuxer",
        subFile = "sub-file",
        subfile = "subfile",
        subFilePaths = "sub-file-paths",
        subFiles = "sub-files",
        subFilterSdh = "sub-filter-sdh",
        subFilterSdhHarder = "sub-filter-sdh-harder",
        subFixTiming = "sub-fix-timing",
        subFont = "sub-font",
        subfont = "subfont",
        subFontSize = "sub-font-size",
        subfontTextScale = "subfont-text-scale",
        subForcedOnly = "sub-forced-only",
        subFps = "sub-fps",
        subfps = "subfps",
        subFuzziness = "sub-fuzziness",
        subGauss = "sub-gauss",
        subGray = "sub-gray",
        subItalic = "sub-italic",
        subJustify = "sub-justify",
        subMarginX = "sub-margin-x",
        subMarginY = "sub-margin-y",
        subPos = "sub-pos",
        subpos = "subpos",
        subScale = "sub-scale",
        subScaleByWindow = "sub-scale-by-window",
        subScaleWithWindow = "sub-scale-with-window",
        subShadowColor = "sub-shadow-color",
        subShadowOffset = "sub-shadow-offset",
        subSpacing = "sub-spacing",
        subSpeed = "sub-speed",
        subText = "sub-text",
        subTextAlignX = "sub-text-align-x",
        subTextAlignY = "sub-text-align-y",
        subTextBackColor = "sub-text-back-color",
        subTextBlur = "sub-text-blur",
        subTextBold = "sub-text-bold",
        subTextBorderColor = "sub-text-border-color",
        subTextBorderSize = "sub-text-border-size",
        subTextColor = "sub-text-color",
        subTextFont = "sub-text-font",
        subTextFontSize = "sub-text-font-size",
        subTextItalic = "sub-text-italic",
        subTextMarginX = "sub-text-margin-x",
        subTextMarginY = "sub-text-margin-y",
        subTextShadowColor = "sub-text-shadow-color",
        subTextShadowOffset = "sub-text-shadow-offset",
        subTextSpacing = "sub-text-spacing",
        subUseMargins = "sub-use-margins",
        subVisibility = "sub-visibility",
        swapchainDepth = "swapchain-depth",
        swsCgb = "sws-cgb",
        swsChs = "sws-chs",
        swsCs = "sws-cs",
        swsCvs = "sws-cvs",
        swsLgb = "sws-lgb",
        swsLs = "sws-ls",
        swsScaler = "sws-scaler",
        targetPrim = "target-prim",
        targetTrc = "target-trc",
        taskbarProgress = "taskbar-progress",
        teletextPage = "teletext-page",
        temporalDither = "temporal-dither",
        temporalDitherPeriod = "temporal-dither-period",
        terminal = "terminal",
        termOsd = "term-osd",
        termOsdBar = "term-osd-bar",
        termOsdBarChars = "term-osd-bar-chars",
        termPlayingMsg = "term-playing-msg",
        termStatusMsg = "term-status-msg",
        timePos = "time-pos",
        timeRemaining = "time-remaining",
        timeStart = "time-start",
        title = "title",
        tlsCaFile = "tls-ca-file",
        tlsCertFile = "tls-cert-file",
        tlsKeyFile = "tls-key-file",
        tlsVerify = "tls-verify",
        toneMapping = "tone-mapping",
        toneMappingDesaturate = "tone-mapping-desaturate",
        toneMappingParam = "tone-mapping-param",
        totalAvsyncChange = "total-avsync-change",
        trackAutoSelection = "track-auto-selection",
        trackList = "track-list",
        tscale = "tscale",
        tscaleAntiring = "tscale-antiring",
        tscaleBlur = "tscale-blur",
        tscaleClamp = "tscale-clamp",
        tscaleCutoff = "tscale-cutoff",
        tscaleParam1 = "tscale-param1",
        tscaleParam2 = "tscale-param2",
        tscaleRadius = "tscale-radius",
        tscaleTaper = "tscale-taper",
        tscaleWblur = "tscale-wblur",
        tscaleWindow = "tscale-window",
        tscaleWparam = "tscale-wparam",
        tscaleWtaper = "tscale-wtaper",
        tvBrightness = "tv-brightness",
        tvChannel = "tv-channel",
        tvContrast = "tv-contrast",
        tvFreq = "tv-freq",
        tvHue = "tv-hue",
        tvNorm = "tv-norm",
        tvSaturation = "tv-saturation",
        tvScan = "tv-scan",
        tvscan = "tvscan",
        untimed = "untimed",
        useEmbeddedIccProfile = "use-embedded-icc-profile",
        useFiledirConf = "use-filedir-conf",
        userAgent = "user-agent",
        vd = "vd",
        vdLavcBitexact = "vd-lavc-bitexact",
        vdLavcCheckHwProfile = "vd-lavc-check-hw-profile",
        vdLavcDr = "vd-lavc-dr",
        vdLavcFast = "vd-lavc-fast",
        vdLavcFramedrop = "vd-lavc-framedrop",
        vdLavcO = "vd-lavc-o",
        vdLavcShowAll = "vd-lavc-show-all",
        vdLavcSkipframe = "vd-lavc-skipframe",
        vdLavcSkipidct = "vd-lavc-skipidct",
        vdLavcSkiploopfilter = "vd-lavc-skiploopfilter",
        vdLavcSoftwareFallback = "vd-lavc-software-fallback",
        vdLavcThreads = "vd-lavc-threads",
        vf = "vf",
        vfDefaults = "vf-defaults",
        vfMetadata = "vf-metadata",
        vid = "vid",
        video = "video",
        videoAlignX = "video-align-x",
        videoAlignY = "video-align-y",
        videoAspect = "video-aspect",
        videoAspectMethod = "video-aspect-method",
        videoBitrate = "video-bitrate",
        videoCodec = "video-codec",
        videoDecParams = "video-dec-params",
        videoFormat = "video-format",
        videoFrameInfo = "video-frame-info",
        videoOsd = "video-osd",
        videoOutParams = "video-out-params",
        videoOutputLevels = "video-output-levels",
        videoPanX = "video-pan-x",
        videoPanY = "video-pan-y",
        videoParams = "video-params",
        videoRotate = "video-rotate",
        videoSpeedCorrection = "video-speed-correction",
        videoStereoMode = "video-stereo-mode",
        videoSync = "video-sync",
        videoSyncAdropSize = "video-sync-adrop-size",
        videoSyncMaxAudioChange = "video-sync-max-audio-change",
        videoSyncMaxVideoChange = "video-sync-max-video-change",
        videotoolboxFormat = "videotoolbox-format",
        videoUnscaled = "video-unscaled",
        videoZoom = "video-zoom",
        vlang = "vlang",
        vo = "vo",
        voConfigured = "vo-configured",
        voDelayedFrameCount = "vo-delayed-frame-count",
        voDropFrameCount = "vo-drop-frame-count",
        voImageFormat = "vo-image-format",
        voImageHighBitDepth = "vo-image-high-bit-depth",
        voImageJpegQuality = "vo-image-jpeg-quality",
        voImageJpegSourceChroma = "vo-image-jpeg-source-chroma",
        voImageOutdir = "vo-image-outdir",
        voImagePngCompression = "vo-image-png-compression",
        voImagePngFilter = "vo-image-png-filter",
        voImageTagColorspace = "vo-image-tag-colorspace",
        volume = "volume",
        volumeMax = "volume-max",
        voNullFps = "vo-null-fps",
        voPasses = "vo-passes",
        voTct256 = "vo-tct-256",
        voTctAlgo = "vo-tct-algo",
        voTctHeight = "vo-tct-height",
        voTctWidth = "vo-tct-width",
        vsyncJitter = "vsync-jitter",
        vsyncRatio = "vsync-ratio",
        watchLaterDirectory = "watch-later-directory",
        wid = "wid",
        width = "width",
        windowDragging = "window-dragging",
        windowMinimized = "window-minimized",
        windowScale = "window-scale",
        workingDirectory = "working-directory",
        writeFilenameInWatchLaterConfig = "write-filename-in-watch-later-config",
        x11Name = "x11-name",
        ytdl = "ytdl",
        ytdlFormat = "ytdl-format",
        ytdlRawOptions = "ytdl-raw-options",
        assShaper = "ass-shaper",
        assStyleOverride = "ass-style-override",
        assScaleWithWindow = "ass-scale-with-window",
        subAssStyleOverride = "sub-ass-style-override",
        subPaths = "sub-paths",
    }
}

function createRevMap(enumType) {
    let res = {};
    for (let name in enumType) {
        res[enumType[name]] = name;
    }
    return res
}

let propertyReverseMap = createRevMap(mpv.Property);
let trackPropertyReverseMap = createRevMap(mpv.TrackDataProp);

export default mpv;
